services:
  my_frontend:
    container_name: my_frontend
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    ports:
      - "32768:8000"
    volumes:
      - .:/var/www/html/app
    tty: true